import json
import os
from time import sleep
import requests
from dotenv import load_dotenv, find_dotenv

load_dotenv(find_dotenv())

ORG_NAME = "csc4350-sp22"


def get_id_by_username(username):
    id_response = requests.get(
        f"https://api.github.com/users/{username}",
        headers={
            "Accept": "application/vnd.github.v3+json",
            "Authorization": f"token {os.getenv('GH_TOKEN')}",
        },
    )
    id_response = id_response.json()
    return id_response["id"]


def add_id_to_org(user_id):
    return requests.post(
        f"https://api.github.com/orgs/{ORG_NAME}/invitations",
        headers={
            "Accept": "application/vnd.github.v3+json",
            "Authorization": f"token {os.getenv('GH_TOKEN')}",
        },
        data=json.dumps(
            {
                "invitee_id": user_id,
            }  # needed to use json function to get GH to accept request body
        ),
    )


if __name__ == "__main__":
    """
    Take file generated by hw2_username_extractor.py and add each username
    to the class GH org.
    """
    with open("github_usernames.txt") as f:
        for line in f:
            username = line.strip()
            user_id = get_id_by_username(username)
            response = add_id_to_org(user_id)
            if response.status_code != 201:
                print(f"Couldn't add user {line} to org: {response.json()}")
                break
            sleep(1)  # try not to get rate-limited
